SELECT 
    COMPANY_CODE,
    FOUNDER,
    (
        SELECT COUNT(DISTINCT LEAD_MANAGER_CODE) FROM LEAD_MANAGER AS L WHERE L.COMPANY_CODE = C.COMPANY_CODE
    ),
    (
        SELECT COUNT(DISTINCT SENIOR_MANAGER_CODE) FROM SENIOR_MANAGER AS S WHERE S.COMPANY_CODE = C.COMPANY_CODE
    ),
    (
        SELECT COUNT(DISTINCT MANAGER_CODE) FROM MANAGER AS M WHERE M.COMPANY_CODE = C.COMPANY_CODE
    ),
    (
        SELECT COUNT(DISTINCT EMPLOYEE_CODE) FROM EMPLOYEE AS E WHERE E.COMPANY_CODE = C.COMPANY_CODE
    )
FROM 
    COMPANY AS C
ORDER BY 
    COMPANY_CODE ASC;
